# Generated by Django 2.2.6 on 2019-11-11 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20191014_1850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transections',
            options={'ordering': ['date']},
        ),
    ]
