# Generated by Django 2.2.5 on 2019-10-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
