# Generated by Django 2.2.5 on 2019-10-06 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item_register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp_Item_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('is_buy', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item_register.Item')),
            ],
        ),
    ]
