# Generated by Django 2.2.5 on 2019-10-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_register', '0002_temp_item_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='total_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
