# Generated by Django 2.2.6 on 2019-11-11 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_register', '0002_bill_remarks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['item_id']},
        ),
    ]
